### ISSUE TITLE
# symbol in directory name causes issues.

### ISSUE THREAD

**Issue by GaryFDes** [klaussilveira/gitlist#514]
We have a directory in our repo that has the name C# and this directory name gives gitlist problems when browsing into the  directory.  The # symbol should be encoded.

**Comment by garygreen** [comment]
This has been fixed already with the use of `preg_quote`

**Comment by fauxpark** [comment]
@garygreen your PR (#554) doesn't fix this issue. The # symbol is not part of [the regex special character set](http://php.net/manual/en/function.preg-quote.php) and thus doesn't get escaped. Plus, getRepositoryRegex only applies to the repository name, not the directories/files in it -- for that you need to look at the ArgumentEscaper class.

**Comment by garygreen** [comment]
Ahh. That's because Symphony uses the `#` character as PCRE seperator for route matching. I've updated PR #554 please let me know if this fixes your issue @erez-o @fauxpark
